= Configuration Migration
:navtitle: Configuration Migration

Axon Framework 5 restructures the configuration system, splitting the monolithic `Configurer` into focused configurers and replacing the `ConfigurerModule` with the `ConfigurationEnhancer`.

This path covers the migration of configuration-related code from Axon Framework 4 to Axon Framework 5. For extensive details on how the configuration work in Axon Framework 5, please check out the xref:configuration:index.adoc[Configuration chapter].

[NOTE]
====
The most significant changes are:

* **Configurer split**: The single `Configurer` has been replaced by `MessagingConfigurer`, `ModellingConfigurer`, and `EventSourcingConfigurer`, as explained in more detail xref:configuration:configurer.adoc[here]
* **ConfigurerModule replacement**: `ConfigurerModule` has been replaced by `ConfigurationEnhancer`, which operates on a xref:configuration:registries.adoc#component-registry[`ComponentRegistry`]
* **Component registration**: Several component-specific `Configurer` registration methods have been replaced for generic registration methods on the xref:configuration:registries.adoc#component-registry[`ComponentRegistry`]
* **Lifecycle registration**: Lifecycle handlers are now registered through the xref:configuration:registries.adoc#lifecycle-registry[`LifecycleRegistry`]
====

[#configurer_adjustments]
== `Configurer` adjustments

The `Configurer` and `DefaultConfigurer` from Axon Framework 4 have been replaced by three focused configurers in Axon Framework 5, called `ApplicationConfigurers`, each corresponding to a layer of the framework.
Choose the one that matches the highest-level feature your application uses:

* `MessagingConfigurer` - for applications that only require messaging (commands, events, queries)
* `ModellingConfigurer` - adds entity (formerly aggregate) and repository support on top of messaging
* `EventSourcingConfigurer` - adds event sourcing and event store support on top of modelling

These configurers form a delegation chain: `EventSourcingConfigurer` wraps `ModellingConfigurer`, which wraps `MessagingConfigurer`.
When Axon Framework is combined with <<spring_boot_configuration,Spring>> you will typically never have to interact with any of these `ApplicationConfigurer` types.
Instead, you take Spring's bean creation approach or adjust the configuration through the `ConfigurationEnhancer`, as explained <<configurermodule_to_configurationenhancer,here>> in more detail.

When you are using Axon Framework 4's `Configurer` directly, please check the following examples on how to migrate:

[tabs]
====
Axon Framework 4::
+
[source,java,role=axon4]
----
import org.axonframework.config.Configuration;
import org.axonframework.config.Configurer;
import org.axonframework.config.DefaultConfigurer;

class AxonApp {

    public static void main(String[] args) {
        Configurer configurer = DefaultConfigurer.defaultConfiguration();
        // Register components, aggregates, event handlers...

        Configuration configuration = configurer.buildConfiguration();
        configuration.start();
    }
}
----

Axon Framework 5::
+
[source,java]
----
include::example$migration/paths/configuration/eventsourcingsetup/AxonApp.java[tag=eventsourcing-configurer-setup,indent=0]
----
+
If your application does not use event sourcing, use the configurer that matches your needs:
+
[source,java]
----
include::example$migration/paths/configuration/configurervariants/ConfigurerVariants.java[tag=configurer-variants,indent=0]
----
====

Each configurer provides escape-hatch methods to access the underlying layer when needed:

[source,java]
----
include::example$migration/paths/configuration/escapehatches/AxonApp.java[tag=configurer-escape-hatches,indent=0]
----

[#configurermodule_to_configurationenhancer]
== `ConfigurerModule` to `ConfigurationEnhancer`

The `ConfigurerModule` interface from Axon Framework 4 allowed modules to hook into the configuration process.
This feature was especially useful for Axon applications that integrate with <<spring_boot_configuration,Spring>>, as it allows for a hook to customize the configuration.
In Axon Framework 5, this concept has been renamed and slightly adjusted to the `ConfigurationEnhancer`.

Largest difference between both, is that the latter deals with the xref:configuration:registries.adoc#component-registry[`ComponentRegistry`] (used under the hood by the `ApplicationConfigurer` as defined <<configurer_adjustments,here>>).
The `ConfigurationEnhancer` has an `order()` method, just as the `ConfigurerModule.` did, which dictates the order in which the module acts on the configurer directly.
Furthermore, just as the `ConfigurerModule`, the `ConfigurationEnhancer` can be registered through the Service Loader mechanism, directly with the configurer, or as a Spring bean.

Let us look at an example use of the `ConfigurerModule` and what this would look like as a `ConfigurationEnhancer`:

[tabs]
====
Axon Framework 4::
+
[source,java,role=axon4]
----
import org.axonframework.config.Configurer;
import org.axonframework.config.ConfigurerModule;

public class MyConfigurerModule implements ConfigurerModule {

    @Override
    public void configureModule(Configurer configurer) {
        configurer.registerComponent(MyService.class, config -> new MyService());
    }
}
----
+

Axon Framework 5::
+
[source,java]
----
include::example$migration/paths/configuration/configurationenhancer/MyConfigurationEnhancer.java[tag=configuration-enhancer,indent=0]
----
+
====

[#component_registration_via_componentregistry]
== Component registration via `ComponentRegistry`

In Axon Framework 4, components were registered through dedicated methods on the `Configurer`.
In Axon Framework 5, some of these methods have been replaced for generic methods on the `ComponentRegistry`, accessible from any configurer.
Exception to this rule are made, like registration of the `CommandBus` or `EventStore`.
Registration methods for these reside on their respective `ApplicationConfigurer` level (as explained shortly <<configurer_adjustments,here>>).
As such, the `CommandBus` has a dedicated registration method on the `MessagingConfigurer`, whereas the `EventStore` has one on the `EventSourcingConfigurer`.

If you are unable to find the specific registration methods, do not worry.
At the core of Axon's configuration sits the xref:configuration:registries.adoc#component-registry[`ComponentRegistry`] with its generic registration operation.
The specific registration methods are thus just convenience methods, or syntactic sugar, overlaying the `ComponentRegistry`.

Let's look at some configuration solutions in Axon Framework 4 to see what they should look like in Axon Framework 5:

[tabs]
====
Axon Framework 4::
+
[source,java,role=axon4]
----
import org.axonframework.commandhandling.SimpleCommandBus;
import org.axonframework.config.Configurer;
import org.axonframework.config.DefaultConfigurer;

class AxonApp {

    public static void main(String[] args) {
        Configurer configurer = DefaultConfigurer.defaultConfiguration();

        // Register a custom component
        configurer.registerComponent(MyService.class, config -> new MyService());

        // Register a command bus
        configurer.configureCommandBus(config -> SimpleCommandBus.builder().build());
    }
}
----

Axon Framework 5::
+
[source,java]
----
include::example$migration/paths/configuration/componentregistration/AxonApp.java[tag=component-registration,indent=0]
----
====

Besides plain registration, the `ComponentRegistry` supports conditional registration to prevents overwriting previously registered components:

[source,java]
----
include::example$migration/paths/configuration/conditionalregistration/AxonApp.java[tag=conditional-registration,indent=0]
----

For richer component definitions with <<lifecycle_handler_registration,lifecycle hooks>>, use `ComponentDefinition`:

[source,java]
----
include::example$migration/paths/configuration/componentdefinition/AxonApp.java[tag=component-definition,indent=0]
----

[#lifecycle_handler_registration]
== Lifecycle handler registration

In Axon Framework 4, lifecycle handlers like `onStart` or `onShutdown` were registered directly on the `Configurer`.
In Axon Framework 5, these have moved to the xref:configuration:registries.adoc#lifecycle-registry[`LifecycleRegistry`], accessible from any configurer via the `lifecycleRegistry` method:

[tabs]
====
Axon Framework 4::
+
[source,java,role=axon4]
----
import org.axonframework.common.lifecycle.Phase;
import org.axonframework.config.Configurer;
import org.axonframework.config.DefaultConfigurer;

import java.util.concurrent.CompletableFuture;

class AxonApp {

    public static void main(String[] args) {
        Configurer configurer = DefaultConfigurer.defaultConfiguration();

        configurer.onStart(Phase.LOCAL_MESSAGE_HANDLER_REGISTRATIONS, () -> {
            // Startup logic
            return CompletableFuture.completedFuture(null);
        });

        configurer.onShutdown(Phase.LOCAL_MESSAGE_HANDLER_REGISTRATIONS, () -> {
            // Shutdown logic
            return CompletableFuture.completedFuture(null);
        });
    }
}
----

Axon Framework 5::
+
[source,java]
----
include::example$migration/paths/configuration/lifecycleregistry/AxonApp.java[tag=lifecycle-registry,indent=0]
----
====

Start and shutdown handlers are, however, in most cases tied to the component you want to configure.
You could configure this in Axon Framework 4 by having a component implement the `Lifecycle` interface.
This interface no longer exists in Axon Framework 5. Instead, lifecycle handler registration is integrated into component registration:

[tabs]
====
Axon Framework 4::
+
[source,java,role=axon4]
----
import org.axonframework.common.lifecycle.Phase;
import org.axonframework.lifecycle.Lifecycle;
import org.jetbrains.annotations.NotNull;

class MyComponent implements Lifecycle {

    @Override
    public void registerLifecycleHandlers(@NotNull Lifecycle.LifecycleRegistry lifecycle) {
        lifecycle.onStart(Phase.LOCAL_MESSAGE_HANDLER_REGISTRATIONS, () -> {});
        lifecycle.onShutdown(Phase.LOCAL_MESSAGE_HANDLER_REGISTRATIONS, () -> {});
    }
}
----

Axon Framework 5::
+
[source,java]
----
include::example$migration/paths/configuration/componentlifecycle/AxonApp.java[tag=component-lifecycle,indent=0]
----
====

[#spring_boot_configuration]
== Spring Boot configuration

When using Spring Boot, the auto-configuration automatically sets up the appropriate configurer.
Moving from the `ConfigurerModule` to the `ConfigurationEnhancer` (as explained <<configurermodule_to_configurationenhancer,here>>) in your beans is arguably most important:

[tabs]
====
Axon Framework 4::
+
[source,java,role=axon4]
----
import org.axonframework.config.ConfigurerModule;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
class AxonConfig {

    @Bean
    public ConfigurerModule myModule() {
        return configurer -> configurer.registerComponent(
                MyService.class,
                config -> new MyService()
        );
    }
}
----

Axon Framework 5::
+
[source,java]
----
include::example$migration/paths/configuration/configurationenhancerspring/AxonConfig.java[tag=configuration-enhancer-spring,indent=0]
----
====